import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Shield, ArrowRight, Loader2, Download, X } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { NDPRConsent } from './NDPRConsent';

const SESSION_KEY = 'sentinel_exit_intent_shown';

const ROADMAP_CONTENT = `CBN AML COMPLIANCE ROADMAP TEMPLATE
Circular: BSD/DIR/PUB/LAB/019/002
Submission Deadline: June 10, 2026

Generated by Sentinel — sentinel.ng
`;

interface Props {
  daysRemaining: number;
}

export function ExitIntentModal({ daysRemaining }: Props) {
  const [open, setOpen] = useState(false);
  const [email, setEmail] = useState('');
  const [consent, setConsent] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    // Desktop only — skip touch devices and small viewports.
    if (typeof window === 'undefined') return;
    const isTouch = window.matchMedia('(hover: none)').matches || window.innerWidth < 1024;
    if (isTouch) return;
    if (sessionStorage.getItem(SESSION_KEY) === '1') return;

    const handler = (e: MouseEvent) => {
      if (e.clientY < 20 && !e.relatedTarget) {
        if (sessionStorage.getItem(SESSION_KEY) === '1') return;
        sessionStorage.setItem(SESSION_KEY, '1');
        setOpen(true);
      }
    };
    document.addEventListener('mouseleave', handler);
    return () => document.removeEventListener('mouseleave', handler);
  }, []);

  const triggerDownload = () => {
    const blob = new Blob([ROADMAP_CONTENT], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'CBN_AML_Roadmap_Template_Sentinel.pdf';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (submitting || !consent) return;
    const trimmed = email.trim();
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed)) {
      toast({ title: 'Invalid email', description: 'Please enter a valid work email.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    const { error } = await supabase.from('leads').insert({
      email: trimmed,
      source: 'exit_intent',
      ndpr_consent: consent,
    });
    setSubmitting(false);
    if (error) {
      toast({ title: 'Submission failed', description: 'Please try again.', variant: 'destructive' });
      return;
    }
    triggerDownload();
    toast({ title: 'Download started', description: 'Your CBN roadmap template is downloading.' });
    setOpen(false);
  };

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          className="fixed inset-0 z-[100] flex items-center justify-center px-6"
          style={{ backgroundColor: 'rgba(0,0,0,0.6)' }}
          onClick={() => setOpen(false)}
        >
          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.96 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 10, scale: 0.98 }}
            transition={{ duration: 0.25, ease: 'easeOut' }}
            onClick={(e) => e.stopPropagation()}
            className="relative w-full max-w-md rounded-2xl border border-white/10 bg-[hsl(220,25%,10%)] p-7 shadow-[0_0_60px_-10px_hsl(var(--primary)/0.35)]"
          >
            <button
              type="button"
              onClick={() => setOpen(false)}
              aria-label="Close"
              className="absolute right-3 top-3 h-8 w-8 flex items-center justify-center rounded-md text-white/40 hover:text-white hover:bg-white/5 transition-colors"
            >
              <X className="h-4 w-4" />
            </button>

            <div className="space-y-5">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/15 border border-primary/25 text-primary">
                <Shield className="h-7 w-7" strokeWidth={1.75} />
              </div>

              <div className="space-y-2">
                <h3 className="text-xl font-bold text-white tracking-tight leading-tight">
                  Before you go — the CBN deadline is in {daysRemaining} days
                </h3>
                <p className="text-sm text-white/55 leading-relaxed">
                  Download our free roadmap template — pre-formatted for Circular{' '}
                  <span className="text-white/75 font-mono text-xs">BSD/DIR/PUB/LAB/019/002</span>. Takes 2 hours to complete. Used by 50+ institutions.
                </p>
              </div>

              <form onSubmit={handleSubmit} className="space-y-3">
                <Input
                  type="email"
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="you@institution.com"
                  aria-label="Work email"
                  maxLength={255}
                  autoFocus
                  className="bg-white/[0.04] border-white/10 text-white placeholder:text-white/25 h-11 rounded-lg"
                />
                <Button
                  type="submit"
                  disabled={submitting || !consent}
                  className="w-full bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg h-11 font-semibold group disabled:opacity-40"
                >
                  {submitting ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <>
                      <Download className="h-4 w-4" />
                      Download Free Template
                      <ArrowRight className="h-4 w-4 group-hover:translate-x-0.5 transition-transform" />
                    </>
                  )}
                </Button>
                <NDPRConsent checked={consent} onCheckedChange={setConsent} id="ndpr-exit" />
              </form>

              <button
                type="button"
                onClick={() => setOpen(false)}
                className="block w-full text-center text-xs text-white/30 hover:text-white/60 transition-colors"
              >
                No thanks, I'll figure it out myself
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
