import { useState, useMemo } from 'react';
import { motion } from 'framer-motion';
import { FileText, ArrowRight, Loader2, CheckCircle2, Download, CreditCard, Layers } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { WhatsAppIcon } from './WhatsAppIcon';
import { WHATSAPP_URL } from '@/lib/whatsapp';
import { NDPRConsent } from './NDPRConsent';

const ROADMAP_CONTENT = `CBN AML COMPLIANCE ROADMAP TEMPLATE
Circular: BSD/DIR/PUB/LAB/019/002
Submission Deadline: June 10, 2026

================================================================
SECTION 1 — INSTITUTION PROFILE
================================================================
Institution Name:        ____________________________________
License Type:            DMB / Fintech / PSP / MMO / MFB / IMTO
Compliance Officer:      ____________________________________
NFIU Reporting ID:       ____________________________________

================================================================
SECTION 2 — TEN CBN CAPABILITY AREAS — GAP ASSESSMENT
================================================================
[ ] 1. Customer Due Diligence (CDD) — tiered KYC with BVN/NIN
[ ] 2. Enhanced Due Diligence (EDD) for high-risk customers
[ ] 3. PEP & sanctions screening (UN/OFAC/EU/NFIU domestic)
[ ] 4. Beneficial ownership identification
[ ] 5. Transaction monitoring (Nigerian typology rule library)
[ ] 6. Suspicious Transaction Reporting (NFIU goAML XML)
[ ] 7. Currency Transaction Reporting (CTR)
[ ] 8. Independent audit & immutable trail
[ ] 9. AML/CFT training programme & board oversight
[ ] 10. Record retention (5-year minimum, examiner-ready)

================================================================
SECTION 3 — REMEDIATION TIMELINE
================================================================
Weeks 1-2:   Gap analysis & risk assessment
Weeks 3-5:   Policy & procedure refresh
Weeks 6-9:   Technology deployment & rule tuning
Weeks 10-11: Staff training & UAT
Week 12:     Internal audit & CBN attestation

================================================================
SECTION 4 — SIGN-OFF
================================================================
Compliance Officer: ___________________  Date: _______________
Chief Risk Officer: ___________________  Date: _______________
Managing Director:  ___________________  Date: _______________

Generated by Sentinel — sentinel.ng
`;

export function RoadmapLeadMagnet() {
  const [email, setEmail] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [done, setDone] = useState(false);
  const [consent, setConsent] = useState(false);
  const { toast } = useToast();

  const urgencyDate = useMemo(() => {
    const d = new Date();
    d.setDate(d.getDate() + 30);
    return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  }, []);

  const triggerDownload = () => {
    const blob = new Blob([ROADMAP_CONTENT], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'CBN_AML_Roadmap_Template_Sentinel.pdf';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (submitting || !consent) return;
    const trimmed = email.trim();
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed)) {
      toast({ title: 'Invalid email', description: 'Please enter a valid work email.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    const { error } = await supabase.from('leads').insert({
      email: trimmed,
      source: 'roadmap_magnet',
      ndpr_consent: consent,
    });
    setSubmitting(false);
    if (error) {
      toast({ title: 'Submission failed', description: 'Please try again.', variant: 'destructive' });
      return;
    }
    setDone(true);
    triggerDownload();
    toast({ title: 'Download started', description: 'Your CBN roadmap template is downloading.' });
  };

  return (
    <section className="relative px-6 py-12">
      <div className="mx-auto max-w-6xl">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-80px' }}
          transition={{ duration: 0.5, ease: 'easeOut' }}
          className="relative rounded-2xl border border-white/[0.06] border-l-4 border-l-primary bg-[hsl(220,25%,10%)] shadow-[0_0_60px_-20px_hsl(var(--primary)/0.25)] overflow-hidden"
        >
          <div className="absolute inset-y-0 left-0 w-32 bg-gradient-to-r from-primary/[0.06] to-transparent pointer-events-none" />

          <div className="relative grid gap-8 lg:grid-cols-[1.1fr_1fr] p-6 sm:p-8 lg:p-10">
            {/* LEFT — Pitch */}
            <div className="space-y-4">
              <div className="flex items-start gap-4">
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-primary/15 border border-primary/25 text-primary">
                  <FileText className="h-7 w-7" strokeWidth={1.75} />
                </div>
                <div className="space-y-2">
                  <p className="inline-flex items-center gap-1.5 rounded-full bg-primary/10 border border-primary/25 px-2.5 py-0.5 text-[10px] uppercase tracking-wider font-semibold text-primary">
                    Free Resource
                  </p>
                  <h3 className="text-2xl md:text-3xl font-bold text-white tracking-tight leading-tight">
                    CBN AML Roadmap Template
                  </h3>
                  <p className="text-sm text-white/55 leading-relaxed max-w-md">
                    Pre-formatted for Circular <span className="text-white/80 font-mono text-[12px]">BSD/DIR/PUB/LAB/019/002</span>. Submit directly to the CBN Compliance Department. Used by 50+ Nigerian compliance teams.
                  </p>
                </div>
              </div>
            </div>

            {/* RIGHT — Form */}
            <div className="space-y-4 lg:pl-8 lg:border-l lg:border-white/[0.06]">
              {done ? (
                <div className="space-y-3">
                  <div className="flex items-center gap-3 rounded-xl border border-risk-low/30 bg-risk-low/10 p-5">
                    <CheckCircle2 className="h-6 w-6 text-risk-low shrink-0" />
                    <div>
                      <p className="text-sm font-semibold text-white">Download started</p>
                      <p className="text-xs text-white/50">Check your downloads folder for the template.</p>
                    </div>
                  </div>
                  <a
                    href={WHATSAPP_URL}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center justify-center gap-2 w-full rounded-lg bg-[#25D366] hover:bg-[#25D366]/90 text-white font-semibold text-sm h-11 px-4 transition-colors group"
                  >
                    <WhatsAppIcon size={18} />
                    Get a faster response — message us on WhatsApp
                    <ArrowRight className="h-4 w-4 group-hover:translate-x-0.5 transition-transform" />
                  </a>
                </div>
              ) : (
                <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-2.5">
                  <Input
                    type="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="you@institution.com"
                    aria-label="Work email"
                    maxLength={255}
                    className="flex-1 bg-white/[0.04] border-white/10 text-white placeholder:text-white/25 h-12 rounded-lg"
                  />
                  <Button
                    type="submit"
                    disabled={submitting}
                    className="bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg h-12 px-5 font-semibold whitespace-nowrap group disabled:opacity-60"
                  >
                    {submitting ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <>
                        <Download className="h-4 w-4" />
                        Download Free Template
                        <ArrowRight className="h-4 w-4 group-hover:translate-x-0.5 transition-transform" />
                      </>
                    )}
                  </Button>
                </form>
              )}

              {/* Trust chips */}
              <div className="flex flex-wrap gap-x-4 gap-y-2">
                {[
                  { icon: CreditCard, label: 'No credit card' },
                  { icon: Download, label: 'Instant download' },
                  { icon: Layers, label: 'Covers all 10 CBN capability areas' },
                ].map(({ icon: Icon, label }) => (
                  <span key={label} className="inline-flex items-center gap-1.5 text-[11px] text-white/45">
                    <Icon className="h-3 w-3 text-white/35" />
                    {label}
                  </span>
                ))}
              </div>

              {/* Urgency */}
              <p className="text-[11px] text-white/35 leading-relaxed pt-1 border-t border-white/[0.04] mt-3 pt-3">
                Most valuable before <span className="text-primary/80 font-medium">{urgencyDate}</span> — deadline pressure increases after that.
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
