import { useState, useMemo, useRef, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/AppSidebar';
import { ThemeToggle } from '@/components/ThemeToggle';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Separator } from '@/components/ui/separator';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Skeleton } from '@/components/ui/skeleton';
import { RiskBadge } from '@/components/RiskBadge';
import { TransactionTimeline } from '@/components/TransactionTimeline';
import { mockAlerts, type AlertData } from '@/data/mockAlerts';
import { useToast } from '@/hooks/use-toast';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Search, SlidersHorizontal, AlertTriangle, Sparkles, Bot, Send, FileDown,
  Loader2, CheckCircle2, Shield, Clock,
} from 'lucide-react';

/* ── Helpers ─────────────────────────────────────────── */

function formatCurrency(amount: number) {
  return new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', minimumFractionDigits: 0 }).format(amount);
}

function generateDraft(alert: AlertData): string {
  const events = alert.transactionTimeline
    .map(
      (e, i) =>
        `   ${i + 1}. ${new Date(e.date).toLocaleDateString('en-GB')} — ${e.type} of ${formatCurrency(e.amount)} via ${e.channel} to/from "${e.counterparty}"${e.flagReason ? ` [Flag: ${e.flagReason}]` : ''}`,
    )
    .join('\n');

  return `SUSPICIOUS TRANSACTION REPORT (STR)
NFIU goAML Format — Draft

═══════════════════════════════════════════

1. CUSTOMER PROFILE
━━━━━━━━━━━━━━━━━━
   Full Name:        ${alert.customerName}
   Customer ID:      ${alert.customerId}
   BVN:              ${alert.bvn}
   Account Number:   ${alert.accountNumber}
   KYC Status:       ${alert.kycTier} — Verified
   Risk Rating:      ${alert.riskLevel} (Score: ${alert.riskScore}/100)

2. SUSPICIOUS ACTIVITY DESCRIPTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Alert Reference:  ${alert.id}
   Alert Type:       ${alert.alertType}
   Total Flagged:    ${formatCurrency(alert.totalFlagged)}
   
   Summary:
   ${alert.summary}

   The above activity deviates from the customer's established transaction
   profile and raises concerns under the Money Laundering (Prohibition)
   Act 2011 (as amended) and CBN AML/CFT Regulations 2023.

3. TRIGGERING EVENTS
━━━━━━━━━━━━━━━━━━━
   ${alert.transactionTimeline.length} transaction(s) flagged:

${events}

4. NFIU FORMATTING & COMPLIANCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Reporting Entity:       SentinelAML Compliance Suite
   Report Category:        Suspicious Transaction Report
   Filing Deadline:        Within 24 hours of determination
   Regulatory Reference:   CBN AML/CFT Regulations 2023, Section 11
   goAML Report Type:      STR
   Priority:               ${alert.riskLevel === 'Critical' ? 'URGENT' : alert.riskLevel === 'High' ? 'HIGH' : 'STANDARD'}

   This report is being filed pursuant to Section 6(1)(b) of the
   Money Laundering (Prohibition) Act 2011 and NFIU Act 2018.

═══════════════════════════════════════════
   Generated by AI STR Co-Pilot • ${new Date().toISOString().split('T')[0]}
   Status: DRAFT — Pending analyst review`;
}

interface ChatMessage {
  id: number;
  role: 'user' | 'assistant';
  content: string;
}

const quickResponses: Record<string, string> = {
  shorter: '✅ Done — I\'ve condensed the Suspicious Activity Description section to a single concise paragraph while preserving all key facts.',
  french: '✅ Done — I\'ve translated the full STR narrative into French while maintaining NFIU field naming conventions.',
  bvn: '✅ Done — I\'ve added BVN mismatch history details under the Customer Profile section.',
  default: '✅ Understood — I\'ve updated the draft accordingly. The changes are highlighted in the editor.',
};

function getResponse(input: string): string {
  const l = input.toLowerCase();
  if (l.includes('short') || l.includes('concise') || l.includes('brief')) return quickResponses.shorter;
  if (l.includes('french') || l.includes('translate')) return quickResponses.french;
  if (l.includes('bvn') || l.includes('mismatch')) return quickResponses.bvn;
  return quickResponses.default;
}

/* ── Alert List Card ─────────────────────────────────── */

function MiniAlertCard({ alert, isSelected, onClick }: { alert: AlertData; isSelected: boolean; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className={`w-full text-left rounded-lg p-3 transition-colors border ${
        isSelected
          ? 'bg-primary/5 border-primary/30 shadow-sm'
          : 'bg-card border-transparent hover:bg-muted/50 hover:border-border'
      }`}
    >
      <div className="flex items-center justify-between mb-1">
        <span className="text-xs font-mono text-muted-foreground">{alert.id}</span>
        <RiskBadge level={alert.riskLevel} />
      </div>
      <p className="text-sm font-medium text-foreground truncate">{alert.customerName}</p>
      <p className="text-xs text-muted-foreground mt-0.5 truncate">{alert.alertType} · {formatCurrency(alert.totalFlagged)}</p>
    </button>
  );
}

/* ── Main Page ───────────────────────────────────────── */

export default function AlertWorkspace() {
  const { toast } = useToast();
  const [searchParams] = useSearchParams();
  const [search, setSearch] = useState('');
  const [selectedId, setSelectedId] = useState<string>(mockAlerts[0].id);

  // STR state
  const [strDraft, setStrDraft] = useState('');
  const [strLoading, setStrLoading] = useState(false);
  const [strGenerated, setStrGenerated] = useState(false);
  const [editVersion, setEditVersion] = useState(0);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  const filtered = useMemo(() => {
    return mockAlerts.filter((a) => {
      const q = search.toLowerCase();
      return (
        a.status === 'Open' || a.status === 'Under Review'
      ) && (
        !q || a.customerName.toLowerCase().includes(q) || a.id.toLowerCase().includes(q)
      );
    });
  }, [search]);

  const selected = filtered.find((a) => a.id === selectedId) || filtered[0];

  // Reset STR state when alert changes
  useEffect(() => {
    setStrDraft('');
    setStrLoading(false);
    setStrGenerated(false);
    setChatMessages([]);
    setEditVersion(0);
  }, [selectedId]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  const handleGenerateSTR = () => {
    if (!selected) return;
    setStrLoading(true);
    setStrDraft('');
    setTimeout(() => {
      setStrDraft(generateDraft(selected));
      setStrLoading(false);
      setStrGenerated(true);
      setChatMessages([{
        id: 1,
        role: 'assistant',
        content: `I've drafted an STR for ${selected.customerName} based on the ${selected.alertType} alert. The report follows NFIU goAML formatting. You can edit directly or ask me to refine it.`,
      }]);
    }, 2500);
  };

  const handleSendChat = () => {
    if (!chatInput.trim()) return;
    const userMsg: ChatMessage = { id: Date.now(), role: 'user', content: chatInput };
    setChatMessages((prev) => [...prev, userMsg]);
    const input = chatInput;
    setChatInput('');
    setIsTyping(true);
    setTimeout(() => {
      setChatMessages((prev) => [...prev, { id: Date.now(), role: 'assistant', content: getResponse(input) }]);
      setIsTyping(false);
      setEditVersion((v) => v + 1);
    }, 1400);
  };

  const handleExport = () => {
    toast({
      title: 'Exporting to goAML XML',
      description: 'STR has been packaged in NFIU goAML XML format and queued for submission.',
    });
  };

  if (!selected) return null;

  return (
    <SidebarProvider>
      <div className="flex min-h-screen w-full bg-background">
        <AppSidebar />
        <div className="flex-1 flex flex-col min-h-0">
          {/* Top bar */}
          <div className="flex items-center justify-between border-b px-6 py-3 bg-card shrink-0">
            <div className="flex items-center gap-2">
              <Shield className="h-5 w-5 text-primary" />
              <h1 className="text-lg font-bold text-foreground">Alert Workspace</h1>
            </div>
            <ThemeToggle />
          </div>

          {/* Split pane */}
          <div className="flex flex-1 min-h-0">
            {/* Left pane – Alert list (30%) */}
            <div className="w-[30%] min-w-[280px] border-r flex flex-col bg-muted/20">
              <div className="p-3 border-b bg-card">
                <div className="relative">
                  <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
                  <Input
                    placeholder="Search open alerts..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    className="pl-8 h-8 text-sm bg-background"
                  />
                </div>
                <p className="text-[11px] text-muted-foreground mt-2">
                  {filtered.length} open alert{filtered.length !== 1 ? 's' : ''}
                </p>
              </div>
              <ScrollArea className="flex-1">
                <div className="p-2 space-y-1">
                  {filtered.map((alert) => (
                    <MiniAlertCard
                      key={alert.id}
                      alert={alert}
                      isSelected={alert.id === selectedId}
                      onClick={() => setSelectedId(alert.id)}
                    />
                  ))}
                </div>
              </ScrollArea>
            </div>

            {/* Right pane – Investigation workspace (70%) */}
            <div className="flex-1 flex flex-col min-h-0 overflow-hidden">
              <ScrollArea className="flex-1">
                <div className="p-6 space-y-6">
                  {/* Triggered Rule Header */}
                  <motion.div
                    key={selected.id}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                  >
                    <Card className="border-l-4 border-l-destructive">
                      <CardContent className="py-4 px-5">
                        <div className="flex items-start justify-between">
                          <div className="space-y-1">
                            <div className="flex items-center gap-2">
                              <AlertTriangle className="h-4 w-4 text-destructive" />
                              <span className="font-semibold text-foreground text-sm">
                                {selected.alertType}: {selected.summary.slice(0, 80)}…
                              </span>
                            </div>
                            <p className="text-xs text-muted-foreground">
                              {selected.id} · {selected.customerName} · Score {selected.riskScore}/100
                            </p>
                          </div>
                          <RiskBadge level={selected.riskLevel} />
                        </div>
                      </CardContent>
                    </Card>
                  </motion.div>

                  {/* Mini Transaction Timeline */}
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-sm font-semibold flex items-center gap-2">
                        <Clock className="h-4 w-4 text-primary" />
                        Triggering Transactions ({selected.transactionTimeline.length})
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <TransactionTimeline events={selected.transactionTimeline.slice(0, 5)} />
                    </CardContent>
                  </Card>

                  <Separator />

                  {/* AI Assistant Section */}
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Sparkles className="h-5 w-5 text-primary" />
                        <h2 className="text-base font-bold text-foreground">AI STR Co-Pilot</h2>
                      </div>
                      {strGenerated && (
                        <Badge variant="outline" className="text-[10px] gap-1">
                          <CheckCircle2 className="h-3 w-3 text-emerald-500" />
                          Draft v{editVersion + 1}
                        </Badge>
                      )}
                    </div>

                    {!strGenerated && !strLoading && (
                      <Card className="border-dashed">
                        <CardContent className="py-10 flex flex-col items-center gap-4">
                          <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10">
                            <Sparkles className="h-7 w-7 text-primary" />
                          </div>
                          <div className="text-center space-y-1.5">
                            <p className="text-sm font-medium text-foreground">Generate an NFIU-formatted STR</p>
                            <p className="text-xs text-muted-foreground max-w-md">
                              AI will analyze the alert data, correlate transactions, and produce a draft Suspicious Transaction Report ready for NFIU goAML submission.
                            </p>
                          </div>
                          <Button size="lg" className="gap-2 mt-2" onClick={handleGenerateSTR}>
                            <Sparkles className="h-4 w-4" /> Generate STR Narrative
                          </Button>
                        </CardContent>
                      </Card>
                    )}

                    {strLoading && (
                      <Card>
                        <CardContent className="py-8 space-y-4">
                          <div className="flex items-center justify-center gap-3">
                            <motion.div animate={{ rotate: 360 }} transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}>
                              <Loader2 className="h-6 w-6 text-primary" />
                            </motion.div>
                            <div>
                              <p className="text-sm font-medium text-foreground">Analyzing transaction network…</p>
                              <p className="text-xs text-muted-foreground">
                                Correlating {selected.transactionTimeline.length} events across compliance databases
                              </p>
                            </div>
                          </div>
                          <div className="flex justify-center gap-2">
                            {['KYC Check', 'PEP Screen', 'Pattern Analysis', 'Drafting'].map((step, i) => (
                              <motion.div key={step} initial={{ opacity: 0.3 }} animate={{ opacity: 1 }} transition={{ delay: i * 0.5 }}>
                                <Badge variant="outline" className="text-[10px]">{step}</Badge>
                              </motion.div>
                            ))}
                          </div>
                          <div className="space-y-2 pt-2">
                            <Skeleton className="h-4 w-full" />
                            <Skeleton className="h-4 w-[90%]" />
                            <Skeleton className="h-4 w-[75%]" />
                            <Skeleton className="h-4 w-full" />
                            <Skeleton className="h-4 w-[60%]" />
                          </div>
                        </CardContent>
                      </Card>
                    )}

                    {strGenerated && (
                      <div className="flex gap-4 min-h-[400px]">
                        {/* Editor */}
                        <div className="flex-1 flex flex-col rounded-lg border overflow-hidden">
                          <div className="px-4 py-2 border-b bg-muted/30 flex items-center justify-between shrink-0">
                            <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">STR Draft Editor</span>
                            <div className="flex items-center gap-2">
                              <Badge variant="outline" className="text-[9px]">Editable</Badge>
                              <Button size="sm" className="h-7 gap-1.5 text-xs" onClick={handleExport}>
                                <FileDown className="h-3 w-3" /> Export to goAML XML
                              </Button>
                            </div>
                          </div>
                          <textarea
                            value={strDraft}
                            onChange={(e) => setStrDraft(e.target.value)}
                            className="flex-1 w-full resize-none bg-background p-4 text-xs font-mono leading-relaxed text-foreground focus:outline-none min-h-[350px]"
                            spellCheck={false}
                          />
                        </div>

                        {/* Chat assistant */}
                        <div className="w-72 flex flex-col rounded-lg border overflow-hidden shrink-0">
                          <div className="px-3 py-2 border-b bg-muted/30 flex items-center gap-2 shrink-0">
                            <Bot className="h-3.5 w-3.5 text-primary" />
                            <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">AI Assistant</span>
                          </div>

                          <ScrollArea className="flex-1 p-3">
                            <div className="space-y-3">
                              <AnimatePresence>
                                {chatMessages.map((msg) => (
                                  <motion.div
                                    key={msg.id}
                                    initial={{ opacity: 0, y: 6 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                                  >
                                    <div className={`max-w-[90%] rounded-lg px-3 py-2 text-xs leading-relaxed ${
                                      msg.role === 'user'
                                        ? 'bg-primary text-primary-foreground'
                                        : 'bg-muted text-foreground'
                                    }`}>
                                      {msg.content}
                                    </div>
                                  </motion.div>
                                ))}
                              </AnimatePresence>
                              {isTyping && (
                                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex justify-start">
                                  <div className="bg-muted rounded-lg px-3 py-2 text-xs text-muted-foreground flex items-center gap-1.5">
                                    <Loader2 className="h-3 w-3 animate-spin" /> Updating draft…
                                  </div>
                                </motion.div>
                              )}
                              <div ref={chatEndRef} />
                            </div>
                          </ScrollArea>

                          <Separator />
                          <div className="p-3 space-y-2 shrink-0">
                            <div className="flex gap-2">
                              <Input
                                placeholder="Ask AI to refine this draft (e.g., make it shorter, translate to French)"
                                value={chatInput}
                                onChange={(e) => setChatInput(e.target.value)}
                                onKeyDown={(e) => e.key === 'Enter' && handleSendChat()}
                                className="h-8 text-xs bg-background"
                              />
                              <Button size="icon" className="h-8 w-8 shrink-0" onClick={handleSendChat} disabled={!chatInput.trim()}>
                                <Send className="h-3.5 w-3.5" />
                              </Button>
                            </div>
                            <div className="flex flex-wrap gap-1">
                              {['Make it shorter', 'Translate to French', 'Add BVN history'].map((s) => (
                                <button
                                  key={s}
                                  onClick={() => setChatInput(s)}
                                  className="text-[10px] px-2 py-0.5 rounded-full border bg-card text-muted-foreground hover:text-foreground hover:border-primary/30 transition-colors"
                                >
                                  {s}
                                </button>
                              ))}
                            </div>
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </ScrollArea>
            </div>
          </div>
        </div>
      </div>
    </SidebarProvider>
  );
}
