import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Severity = 'red' | 'amber' | 'green' | 'blue';

interface FeedEntry {
  id: string;
  time: string;
  severity: Severity;
  message: string;
}

const dotClass: Record<Severity, string> = {
  red: 'bg-[hsl(var(--risk-critical))]',
  amber: 'bg-[hsl(var(--risk-medium))]',
  green: 'bg-[hsl(var(--risk-low))]',
  blue: 'bg-blue-500',
};

const INITIAL_ENTRIES: FeedEntry[] = [
  { id: 'i1', time: '08:43', severity: 'red', message: 'Critical alert — POS Round-Trip detected — Adebayo Ogunlesi — ₦14,800,000' },
  { id: 'i2', time: '08:31', severity: 'amber', message: 'STR draft completed — Case ALT-2026-0891 — Chioma Adeyemi' },
  { id: 'i3', time: '08:15', severity: 'green', message: 'KYC Tier upgrade approved — Fatima Bello — BVN verified' },
  { id: 'i4', time: '07:58', severity: 'blue', message: 'CTR submitted to CBN — 3 transactions above ₦5M threshold' },
  { id: 'i5', time: '07:44', severity: 'red', message: 'High alert — USSD Layering — Chinedu Nwosu — ₦2,340,000' },
  { id: 'i6', time: '07:30', severity: 'green', message: 'Sanctions screen clear — 14 new onboardings' },
  { id: 'i7', time: '07:15', severity: 'amber', message: 'Rule triggered — Dormant Activation — Amina Suleiman — account inactive 14 months' },
  { id: 'i8', time: '06:50', severity: 'red', message: 'Critical — BDC Smurfing pattern — Tunde Bakare — 8 BDC transactions' },
  { id: 'i9', time: '06:30', severity: 'green', message: 'Case closed — STR filed with NFIU — Ref: STR-2026-0041' },
  { id: 'i10', time: '23:58', severity: 'red', message: 'Overnight alert — POS Round-Trip — Adebayo Ogunlesi — IMTO link detected' },
  { id: 'i11', time: '23:22', severity: 'blue', message: 'goAML XML batch transmitted — 7 STRs accepted by NFIU portal' },
  { id: 'i12', time: '22:47', severity: 'amber', message: 'EDD escalation — Ngozi Okonkwo — source-of-funds review opened' },
  { id: 'i13', time: '22:10', severity: 'green', message: 'Case closed — false positive — Yusuf Ibrahim — sanctions hit dismissed' },
  { id: 'i14', time: '21:35', severity: 'red', message: 'Critical — Cross-border smurfing — Emeka Obi — 11 inbound IMTO legs' },
  { id: 'i15', time: '20:58', severity: 'blue', message: 'CTR submitted to CBN — Lagos branch — ₦42,000,000 cash deposit' },
];

const NAMES = [
  'Adebayo Ogunlesi', 'Chioma Adeyemi', 'Fatima Bello', 'Chinedu Nwosu', 'Amina Suleiman',
  'Tunde Bakare', 'Ngozi Okonkwo', 'Yusuf Ibrahim', 'Emeka Obi', 'Zainab Mohammed',
  'Olusegun Adeleke', 'Halima Yakubu', 'Ifeanyi Eze', 'Bukola Adesanya', 'Sadiq Aliyu',
];

const TEMPLATES: { severity: Severity; build: (name: string) => string }[] = [
  { severity: 'red', build: (n) => `Critical alert — POS Structuring — ${n} — ₦${(Math.floor(Math.random() * 90) + 10) * 100_000}`.replace(/000000$/, '00,000') },
  { severity: 'red', build: (n) => `High alert — USSD Layering — ${n} — ₦${(Math.floor(Math.random() * 50) + 5)},${Math.floor(Math.random() * 900) + 100},000` },
  { severity: 'amber', build: (n) => `STR draft updated — ${n} — narrative regenerated by AI Co-Pilot` },
  { severity: 'amber', build: (n) => `Rule triggered — Dormant Activation — ${n} — account inactive ${Math.floor(Math.random() * 18) + 6} months` },
  { severity: 'green', build: (n) => `KYC verification approved — ${n} — BVN + NIN match` },
  { severity: 'green', build: () => `Sanctions screen clear — ${Math.floor(Math.random() * 20) + 3} new onboardings` },
  { severity: 'blue', build: () => `CTR submitted to CBN — ${Math.floor(Math.random() * 5) + 1} transactions above ₦5M threshold` },
  { severity: 'blue', build: () => `goAML XML transmitted — ${Math.floor(Math.random() * 6) + 1} STRs accepted by NFIU portal` },
];

function nowTime(): string {
  return new Date().toLocaleTimeString('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZone: 'Africa/Lagos',
  });
}

export function LiveActivityFeed() {
  const navigate = useNavigate();
  const [entries, setEntries] = useState<FeedEntry[]>(INITIAL_ENTRIES);
  const pausedRef = useRef(false);
  const counterRef = useRef(0);

  useEffect(() => {
    const interval = setInterval(() => {
      if (pausedRef.current) return;
      const tpl = TEMPLATES[Math.floor(Math.random() * TEMPLATES.length)];
      const name = NAMES[Math.floor(Math.random() * NAMES.length)];
      counterRef.current += 1;
      const newEntry: FeedEntry = {
        id: `live-${Date.now()}-${counterRef.current}`,
        time: nowTime(),
        severity: tpl.severity,
        message: tpl.build(name),
      };
      setEntries((prev) => [newEntry, ...prev].slice(0, 30));
    }, 8000);
    return () => clearInterval(interval);
  }, []);

  return (
    <Card className="border-border bg-card shadow-sm flex flex-col">
      <CardHeader className="pb-2 flex flex-row items-center justify-between space-y-0">
        <div>
          <CardTitle className="text-sm font-semibold text-foreground">Live Activity Feed</CardTitle>
          <p className="text-[10px] text-muted-foreground">System-wide compliance events</p>
        </div>
        <div className="flex items-center gap-1.5">
          <span className="relative flex h-2 w-2">
            <span className="absolute inline-flex h-full w-full rounded-full bg-[hsl(var(--risk-low))] opacity-75 animate-ping" />
            <span className="relative inline-flex h-2 w-2 rounded-full bg-[hsl(var(--risk-low))]" />
          </span>
          <span className="text-[10px] font-semibold uppercase tracking-wide text-[hsl(var(--risk-low))]">Live</span>
        </div>
      </CardHeader>
      <CardContent className="pt-0 pb-3 flex-1 flex flex-col">
        <div
          className="flex-1 max-h-[420px] overflow-y-auto pr-1 -mr-1 divide-y divide-border/60"
          onMouseEnter={() => { pausedRef.current = true; }}
          onMouseLeave={() => { pausedRef.current = false; }}
        >
          {entries.map((e) => (
            <div key={e.id} className="flex items-start gap-2.5 py-2 text-[11px] animate-fade-in">
              <span className="text-muted-foreground tabular-nums shrink-0 mt-[2px]">{e.time}</span>
              <span className={`h-2 w-2 rounded-full shrink-0 mt-[5px] ${dotClass[e.severity]}`} />
              <span className="text-foreground leading-snug">{e.message}</span>
            </div>
          ))}
        </div>
        <button
          onClick={() => navigate('/system-audit')}
          className="mt-2 text-[11px] font-medium text-primary hover:underline inline-flex items-center gap-1 self-start"
        >
          View all activity <ArrowRight className="h-3 w-3" />
        </button>
      </CardContent>
    </Card>
  );
}

export default LiveActivityFeed;
