import { useState, useEffect, useRef } from 'react';
import { Bot, Send, FileDown, Loader2, Sparkles, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription,
} from '@/components/ui/sheet';
import { useToast } from '@/hooks/use-toast';
import type { AlertData } from '@/data/mockAlerts';
import { motion, AnimatePresence } from 'framer-motion';

interface ChatMessage {
  id: number;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

function formatCurrency(amount: number) {
  return new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', minimumFractionDigits: 0 }).format(amount);
}

function generateDraft(alert: AlertData): string {
  const events = alert.transactionTimeline
    .map(
      (e, i) =>
        `   ${i + 1}. ${new Date(e.date).toLocaleDateString('en-GB')} — ${e.type} of ${formatCurrency(e.amount)} via ${e.channel} to/from "${e.counterparty}"${e.flagReason ? ` [Flag: ${e.flagReason}]` : ''}`,
    )
    .join('\n');

  return `SUSPICIOUS TRANSACTION REPORT (STR)
NFIU goAML Format — Draft

═══════════════════════════════════════════

1. CUSTOMER PROFILE
━━━━━━━━━━━━━━━━━━
   Full Name:        ${alert.customerName}
   Customer ID:      ${alert.customerId}
   BVN:              ${alert.bvn}
   Account Number:   ${alert.accountNumber}
   KYC Status:       ${alert.kycTier} — Verified
   Risk Rating:      ${alert.riskLevel} (Score: ${alert.riskScore}/100)

2. SUSPICIOUS ACTIVITY DESCRIPTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Alert Reference:  ${alert.id}
   Alert Type:       ${alert.alertType}
   Total Flagged:    ${formatCurrency(alert.totalFlagged)}
   
   Summary:
   ${alert.summary}

   The above activity deviates from the customer's established transaction
   profile and raises concerns under the Money Laundering (Prohibition)
   Act 2011 (as amended) and CBN AML/CFT Regulations 2023.

3. TRIGGERING EVENTS
━━━━━━━━━━━━━━━━━━━
   ${alert.transactionTimeline.length} transaction(s) flagged:

${events}

4. NFIU FORMATTING & COMPLIANCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Reporting Entity:       SentinelAML Compliance Suite
   Report Category:        Suspicious Transaction Report
   Filing Deadline:        Within 24 hours of determination
   Regulatory Reference:   CBN AML/CFT Regulations 2023, Section 11
   goAML Report Type:      STR
   Priority:               ${alert.riskLevel === 'Critical' ? 'URGENT' : alert.riskLevel === 'High' ? 'HIGH' : 'STANDARD'}

   This report is being filed pursuant to Section 6(1)(b) of the
   Money Laundering (Prohibition) Act 2011 and NFIU Act 2018.

═══════════════════════════════════════════
   Generated by AI STR Co-Pilot • ${new Date().toISOString().split('T')[0]}
   Status: DRAFT — Pending analyst review`;
}

const simulatedResponses: Record<string, string> = {
  shorter: '✅ Done — I\'ve condensed the Suspicious Activity Description section to a single concise paragraph while preserving all key facts.',
  bvn: '✅ Done — I\'ve added BVN mismatch history details under the Customer Profile section, including 2 prior BVN discrepancy flags from Jan and Mar 2025.',
  default: '✅ Understood — I\'ve updated the draft accordingly. The changes are highlighted in the editor.',
};

function getSimulatedResponse(input: string): string {
  const lower = input.toLowerCase();
  if (lower.includes('short') || lower.includes('concise') || lower.includes('brief')) return simulatedResponses.shorter;
  if (lower.includes('bvn') || lower.includes('mismatch')) return simulatedResponses.bvn;
  return simulatedResponses.default;
}

interface STRCoPilotDrawerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  alert: AlertData;
}

export function STRCoPilotDrawer({ open, onOpenChange, alert }: STRCoPilotDrawerProps) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(true);
  const [draft, setDraft] = useState('');
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [editVersion, setEditVersion] = useState(0);
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (open) {
      setLoading(true);
      setDraft('');
      setChatMessages([]);
      setEditVersion(0);
      const timer = setTimeout(() => {
        setDraft(generateDraft(alert));
        setLoading(false);
        setChatMessages([
          {
            id: 1,
            role: 'assistant',
            content: `I've drafted an STR for **${alert.customerName}** based on the ${alert.alertType} alert. The report follows NFIU goAML formatting. You can edit the draft directly or ask me to make changes.`,
            timestamp: new Date(),
          },
        ]);
      }, 2500);
      return () => clearTimeout(timer);
    }
  }, [open, alert]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  const handleSendChat = () => {
    if (!chatInput.trim()) return;
    const userMsg: ChatMessage = {
      id: Date.now(),
      role: 'user',
      content: chatInput,
      timestamp: new Date(),
    };
    setChatMessages((prev) => [...prev, userMsg]);
    const input = chatInput;
    setChatInput('');
    setIsTyping(true);

    setTimeout(() => {
      const response = getSimulatedResponse(input);
      setChatMessages((prev) => [
        ...prev,
        { id: Date.now(), role: 'assistant', content: response, timestamp: new Date() },
      ]);
      setIsTyping(false);
      setEditVersion((v) => v + 1);
    }, 1500);
  };

  const handleExport = () => {
    toast({
      title: 'Exporting to goAML Format',
      description: 'STR has been packaged in NFIU goAML XML format and queued for submission.',
    });
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full sm:max-w-4xl p-0 flex flex-col">
        <SheetHeader className="px-6 py-4 border-b bg-card shrink-0">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10">
                <Sparkles className="h-4.5 w-4.5 text-primary" />
              </div>
              <div>
                <SheetTitle className="text-base">AI STR Co-Pilot</SheetTitle>
                <SheetDescription className="text-xs">
                  {alert.id} • {alert.customerName}
                </SheetDescription>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {!loading && (
                <Badge variant="outline" className="text-[10px] gap-1">
                  <CheckCircle2 className="h-3 w-3 text-[hsl(var(--risk-low))]" />
                  Draft v{editVersion + 1}
                </Badge>
              )}
              <Button size="sm" className="gap-1.5" onClick={handleExport} disabled={loading}>
                <FileDown className="h-3.5 w-3.5" />
                Export to NFIU goAML format
              </Button>
            </div>
          </div>
        </SheetHeader>

        {loading ? (
          <div className="flex-1 flex flex-col items-center justify-center gap-4">
            <motion.div
              animate={{ rotate: 360 }}
              transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
            >
              <Loader2 className="h-8 w-8 text-primary" />
            </motion.div>
            <div className="text-center space-y-1.5">
              <p className="text-sm font-medium text-foreground">Analyzing transaction network…</p>
              <p className="text-xs text-muted-foreground">
                Correlating {alert.transactionTimeline.length} events across compliance databases
              </p>
            </div>
            <div className="flex gap-2 mt-2">
              {['KYC Verification', 'PEP Screening', 'Pattern Analysis', 'Draft Generation'].map(
                (step, i) => (
                  <motion.div
                    key={step}
                    initial={{ opacity: 0.3 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: i * 0.6, duration: 0.4 }}
                  >
                    <Badge variant="outline" className="text-[10px]">{step}</Badge>
                  </motion.div>
                ),
              )}
            </div>
          </div>
        ) : (
          <div className="flex-1 flex min-h-0">
            {/* Editor Pane */}
            <div className="flex-1 flex flex-col border-r min-w-0">
              <div className="px-4 py-2.5 border-b bg-muted/30 flex items-center justify-between shrink-0">
                <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
                  STR Draft Editor
                </span>
                <Badge variant="outline" className="text-[9px]">Editable</Badge>
              </div>
              <div className="flex-1 min-h-0">
                <textarea
                  value={draft}
                  onChange={(e) => setDraft(e.target.value)}
                  className="w-full h-full resize-none bg-background p-4 text-xs font-mono leading-relaxed text-foreground focus:outline-none scrollbar-thin"
                  spellCheck={false}
                />
              </div>
            </div>

            {/* Chat Pane */}
            <div className="w-80 flex flex-col shrink-0">
              <div className="px-4 py-2.5 border-b bg-muted/30 flex items-center gap-2 shrink-0">
                <Bot className="h-3.5 w-3.5 text-primary" />
                <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
                  AI Assistant
                </span>
              </div>

              <ScrollArea className="flex-1 p-3">
                <div className="space-y-3">
                  <AnimatePresence>
                    {chatMessages.map((msg) => (
                      <motion.div
                        key={msg.id}
                        initial={{ opacity: 0, y: 8 }}
                        animate={{ opacity: 1, y: 0 }}
                        className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                      >
                        <div
                          className={`max-w-[90%] rounded-lg px-3 py-2 text-xs leading-relaxed ${
                            msg.role === 'user'
                              ? 'bg-primary text-primary-foreground'
                              : 'bg-muted text-foreground'
                          }`}
                        >
                          {msg.content}
                        </div>
                      </motion.div>
                    ))}
                  </AnimatePresence>

                  {isTyping && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="flex justify-start"
                    >
                      <div className="bg-muted rounded-lg px-3 py-2 text-xs text-muted-foreground flex items-center gap-1.5">
                        <Loader2 className="h-3 w-3 animate-spin" />
                        Updating draft…
                      </div>
                    </motion.div>
                  )}
                  <div ref={chatEndRef} />
                </div>
              </ScrollArea>

              <Separator />

              <div className="p-3 shrink-0">
                <div className="flex gap-2">
                  <Input
                    placeholder="e.g. Make the summary shorter…"
                    value={chatInput}
                    onChange={(e) => setChatInput(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleSendChat()}
                    className="h-8 text-xs bg-background"
                  />
                  <Button
                    size="icon"
                    className="h-8 w-8 shrink-0"
                    onClick={handleSendChat}
                    disabled={!chatInput.trim()}
                  >
                    <Send className="h-3.5 w-3.5" />
                  </Button>
                </div>
                <div className="flex flex-wrap gap-1 mt-2">
                  {['Make it shorter', 'Add BVN history', 'Strengthen language'].map((s) => (
                    <button
                      key={s}
                      onClick={() => {
                        setChatInput(s);
                      }}
                      className="text-[10px] px-2 py-0.5 rounded-full border bg-card text-muted-foreground hover:text-foreground hover:border-primary/30 transition-colors"
                    >
                      {s}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}
      </SheetContent>
    </Sheet>
  );
}
